# Generated by Django 2.2.6 on 2019-10-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brassin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_brassin', models.DateField(null=True)),
                ('date_mise_bouteille', models.DateField(blank=True, null=True)),
                ('densite_avant_ebullition', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('densite_initiale', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('densite_finale', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('volume_empatage', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('volume_rincage_dreches', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('volume_mout', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('volume_cuve_fermentation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('nombre_bouteilles', models.IntegerField(blank=True, null=True)),
                ('temps_empatage', models.TimeField(blank=True, null=True)),
                ('temps_ebullition', models.TimeField(blank=True, null=True)),
                ('temps_fermentation', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brassin',
                'ordering': ['date_brassin'],
            },
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ingredient', models.CharField(choices=[('MALT', 'Malt'), ('HOUBLON', 'Houblon'), ('LEVURE', 'Levure'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, null=True)),
                ('variete', models.CharField(max_length=30)),
                ('prix_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('acide_alpha', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ebc_min', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('ebc_max', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('attenuation_min', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('attenuation_max', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'verbose_name': 'Ingredient',
            },
        ),
        migrations.CreateModel(
            name='recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField(null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('client', models.CharField(blank=True, max_length=30, null=True)),
                ('brassin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brassin.brassin')),
            ],
            options={
                'verbose_name': 'Vente',
                'ordering': ['date_vente'],
            },
        ),
        migrations.CreateModel(
            name='brassin_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('temps_infusion', models.TimeField(blank=True, null=True)),
                ('achete', models.BooleanField(default=True)),
                ('brassin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brassin.brassin')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brassin.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='brassin',
            name='ingredient',
            field=models.ManyToManyField(blank=True, null=True, through='brassin.brassin_ingredient', to='brassin.ingredient'),
        ),
        migrations.CreateModel(
            name='achat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField(null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brassin.ingredient')),
            ],
            options={
                'verbose_name': 'Achat',
                'ordering': ['date_achat'],
            },
        ),
    ]
