# Generated by Django 2.2.6 on 2019-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0003_recette_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='densite_desire',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='taux_empatage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='type_biere',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
