# Generated by Django 2.2.6 on 2019-10-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brassin', '0004_auto_20191017_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
